# 02450 - Week 1

No work was needed this week, I added some matrix calculation as brush-up material.

## Notes, theory and working examples

## Exercises

In [3]:
from matplotlib.pyplot import *
import numpy as np
from scipy.io import loadmat

In [4]:
# multiply arrays
a = np.random.rand(2,2)
b = np.array([[2, 0], [0, 2]])
a*b

array([[ 0.88263688,  0.        ],
       [ 0.        ,  0.48577913]])

In [8]:
# convert to matrices and multiply
a = np.asmatrix(a)
b = np.asmatrix(b)
a*b

matrix([[ 0.88263688,  0.72336957],
        [ 1.50672073,  0.48577913]])

Different ways to multiply a matrix, remember the distinction between matrix multiplication and element wise multiplication.

**Proper matrix multiplication**

$$\begin{bmatrix}
       0.4413 & 0.3616 \\[0.3em]
       0.7533 & 0.2428 \\[0.3em] 
  \end{bmatrix}
     \times
  \begin{bmatrix}
       2 & 0 \\[0.3em]
       0 & 2 \\[0.3em] 
  \end{bmatrix}
     \Rightarrow
  \begin{bmatrix}
       0.4413\cdot 2+0.3616\cdot 0 & 0.4413\cdot 0+0.3616\cdot 2 \\[0.3em]
       0.7533\cdot 2+0.2428\cdot 0 & 07533\cdot 0+ 0.2448\cdot 2 \\[0.3em] 
  \end{bmatrix}
     $$

In [9]:
np.dot(a,b) # matrix multiplication

matrix([[ 0.88263688,  0.72336957],
        [ 1.50672073,  0.48577913]])

**Element-wise multiplication**
$$\begin{bmatrix}
       0.4413 & 0.3616 \\[0.3em]
       0.7533 & 0.2428 \\[0.3em] 
  \end{bmatrix}
     \times
  \begin{bmatrix}
       2 & 0 \\[0.3em]
       0 & 2 \\[0.3em] 
  \end{bmatrix}
     \Rightarrow
  \begin{bmatrix}
       2\cdot 0.4413 & 0\cdot 0.3616 \\[0.3em]
       0\cdot 0.7533 & 2\cdot 0.2448 \\[0.3em] 
  \end{bmatrix}
     $$

In [10]:
np.multiply(a,b) # element-wise multiplication x_i*j_i

matrix([[ 0.88263688,  0.        ],
        [ 0.        ,  0.48577913]])